language: node_js
node_js:
  - "6"
env:
  - NODE_ENV=test
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres 
install:
  - npm install sequelize
  - npm install pg
  - npm install pg-hstore
script:
  - sequelize db:migrate
